# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           "/:title/"
relative_permalinks: true

# Setup
title:       'modess.io'
tagline:     ''
description: >
  My name is Niklas Modess, I'm a PHP developer and consultant from Stockholm, Sweden. Author of <a href="http://www.deployingphpapplications.com">Deploying PHP Applications</a>
url:         https://modess.io
baseurl:     /

author:
  name:           'Niklas Modess'
  url:            https://twitter.com/niklasmodess

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
