# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           "/:title/"

# Setup
title:       'modess.io'
tagline:     ''
description: >
  My name is Niklas Modess. I'm a PHP developer and consultant from Stockholm, Sweden.
  I write mostly on deployment, Laravel and PHP in general.
  Author of <a href="http://www.deployingphpapplications.com">Deploying PHP Applications</a> and I occasionally talk at meetups or conferences.
url:         https://modess.io
baseurl:     /

author:
  name:   'Niklas Modess'
  email:   niklas@modess.io
  twitter: niklasmodess
  github:  https://github.com/modess

paginate: 5

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
