# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Permalinks
permalink:        "/:title/"
relative_permalinks: true

# Setup
title:            modess.io
tagline:          ''
description:      >
  <p class="lead">
    My name is Niklas Modess, I'm a PHP developer and consultant from Stockholm, Sweden. Currently a digital nomad living somewhere in the world.
  </p>
  <p class="lead" style="text-align: center;">
    Author of <a href="http://www.deployingphpapplications.com">Deploying PHP Applications</a>.
  </p>
url:              http://modess.io
baseurl:          /

author:
  name:           'Niklas Modess'
  url:            https://twitter.com/niklasmodess

paginate:         5
