# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           "/:title/"

# Setup
title:       'modess.io'
tagline:     ''
description: >
  Hello! My name is Niklas Modess, a PHP developer from Stockholm, Sweden.
  I write mostly on deployment, Laravel, PHP and I'm the author of
  <a href="http://www.deployingphpapplications.com">Deploying PHP Applications</a>.
url:         https://modess.io
enforce_ssl: modess.io
baseurl:     /

author:
  name:   'Niklas Modess'
  email:   niklas@modess.io
  twitter: niklasmodess
  github:  modess

paginate: 5
excerpt_separator: <!-- more -->

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
